// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFGKno7U0JUUN6Fa7lBVitQoNU8xTSZk',
    appId: '1:47211660382:web:0bf3d8d4794a5d3c7160cf',
    messagingSenderId: '47211660382',
    projectId: 'smartlancer-660d4',
    authDomain: 'smartlancer-660d4.firebaseapp.com',
    storageBucket: 'smartlancer-660d4.appspot.com',
    measurementId: 'G-XDBP8P9G72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXGhxMDoFkiBKOXzei_L5DbksV0c1ZDM',
    appId: '1:47211660382:android:7e747f2519574c487160cf',
    messagingSenderId: '47211660382',
    projectId: 'smartlancer-660d4',
    storageBucket: 'smartlancer-660d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RyrHYvn4yobGU64drwnVATr3NtjhV6c',
    appId: '1:47211660382:ios:69abb84a7b0f0b0d7160cf',
    messagingSenderId: '47211660382',
    projectId: 'smartlancer-660d4',
    storageBucket: 'smartlancer-660d4.appspot.com',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_RyrHYvn4yobGU64drwnVATr3NtjhV6c',
    appId: '1:47211660382:ios:2ed064c571c2e3177160cf',
    messagingSenderId: '47211660382',
    projectId: 'smartlancer-660d4',
    storageBucket: 'smartlancer-660d4.appspot.com',
    iosBundleId: 'com.example.chess.RunnerTests',
  );
}
